---
title: 'Lab 7 part 2: spatial interpolation and Kriging'
author: "Alessandra Puig-Santana"
date: "2023-02-23"
output: html_document
---

```{r setup, echo = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(sf)
library(tmap)
library(stars)
library(gstat)
```

## Read in CA depth to groundwater data
```{r}
ca_counties_sf <- read_sf(here("data/ca_counties"),
                               layer = "CA_Counties_TIGER2016") %>%
  janitor::clean_names() %>%
  select(name)

st_crs(ca_counties_sf)

## read in groundwater depth data
ca_dgw_sf <- read_sf(here("data/ca_dgw",
                          "F2013_DBGS_Points_20150720_093252.gpkg")) %>%
  janitor::clean_names()

# st_crs(ca_dgw_sf)

## Transform DGW data to the same CRS as CA Counties 
ca_dgw_sf <- st_transform(ca_dgw_sf, st_crs(ca_counties_sf))

### Make a quick ggplot
ggplot() +
  geom_sf(data = ca_counties_sf) +
  geom_sf(data = ca_dgw_sf, aes(color = dgbs), size = 0.1) +
  scale_color_gradient(low = "pink", high = "darkred")

tmap_mode("view") 
tm_shape(ca_dgw_sf) +
  tm_dots("dgbs", palette = "Blues")

#tmaptools::palette_explorer
```

## Wrangle to just San Joaquin County
```{r}
sj_county_sf <- ca_counties_sf %>%
  filter(name %in% "San Joaquin")

sj_depth_sf <- ca_dgw_sf %>%
  st_intersection(sj_county_sf)

ggplot() +
  geom_sf(data = sj_county_sf) +
  geom_sf(data = sj_depth_sf, 
          aes(color = dgbs)) +
  theme_void() +
  scale_color_viridis_c()
```

## Set up for kriging
```{r}
# removing duplicate combinations

well_duplicates <- sj_depth_sf %>%
  janitor::get_dupes(latitude, longitude) # found duplicates

sj_depth_sf <- sj_depth_sf %>%
  filter(!local_well %in% well_duplicates$local_well) #dropped duplicates
```

## Make a variogram!
```{r}
sj_dgw_vgm <- gstat::variogram(dgbs ~ 1, data = sj_depth_sf)

plot(sj_dgw_vgm)

sj_dgw_vgm_fit <- gstat::fit.variogram(sj_dgw_vgm, 
                                model = vgm(model = "Gau",
                                            nugget = 20,
                                            sill = 3000,
                                            range = 30000))

plot(sj_dgw_vgm, sj_dgw_vgm_fit)

attr(sj_dgw_vgm_fit, "SSErr")
```

## Spatial kriging
```{r}
# start with a grid

sj_grid <- st_bbox(sj_county_sf) %>%
  stars::st_as_stars(dx = 1000, dy = 1000) %>%
  st_crop(sj_county_sf)

plot(sj_grid)
```

```{r}
sj_dgw_krige <- krige(dgbs ~ 1, 
                      sj_depth_sf,
                      sj_grid,
                      model = sj_dgw_vgm_fit)

plot(sj_dgw_krige)
```

