---
title: 'Lab 7: wrangling and visualizing spatial data'
author: "Alessandra Puig-Santana"
date: "2023-02-23"
output: html_document
---

```{r setup, echo = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(broom)

### spatial packages
library(sf)
library(tmap)
```

# Read in CA county outlines
## We are working with vector data right now
```{r}
# sf = simple features
# read_sf = reads vector and sf data files
# reading in the shapefile
ca_counties_sf <- read_sf(here("data/ca_counties/CA_Counties_TIGER2016.shp")) 

ca_subset_sf <- ca_counties_sf %>%
  janitor::clean_names() %>%
  select(county_name = name, 
         land_area = aland) # renaming the columns

ca_subset_df <- ca_subset_sf %>%
  as.data.frame() %>% # we created a df from the sf and removed the sticky geometry
  select(-geometry) # dropped the geometry column from the subset
```

## Check and set the CRS
```{r}
ca_subset_sf %>%
  st_crs()

ggplot() +
  geom_sf(data = ca_subset_sf, 
          aes(fill = land_area),
              color = "white", # white lines for the counties
              size = 0.1) +
  theme_void() + # removing the grid in the background
  scale_fill_gradientn(colors = c("cyan", "blue", "purple")) # making a vector for the gradient
```

## Load another data set on an invasive species 
```{r}
sesbania_sf <- read_sf(here("data", "red_sesbania", "ds80.shp")) %>%
  janitor::clean_names()

sesbania_sf %>%
  st_crs()

sesbania_3857_sf <- st_transform(sesbania_sf, 3857)
```

## Plot the two together
```{r}
# we are doing several geom_sf, the order that you put them is building the map bottom up
ggplot() +
  geom_sf(data = ca_subset_sf, fill = "grey30") +
  geom_sf(data = sesbania_3857_sf, size = 1, color = "red")
```

```{r}
ca_sesb_sf <- ca_subset_sf %>%
  st_join(sesbania_3857_sf) 

sesb_counts_sf <- ca_sesb_sf %>%
  group_by(county_name) %>%
  summarize(n_records = sum(!is.na(id))) # all of those that aren't na, are true and will give us a count
```

## Plot the results
"Chloropleth" map
```{r}
ggplot(data = sesb_counts_sf %>%
         mutate(n_records = ifelse(n_records == 0, NA, n_records))) +
  geom_sf(aes(fill = n_records),
          color = "grey20",
          size = 0.1,
          alpha = 0.4) +
  geom_sf(data = sesbania_3857_sf, color = "blue") +
  scale_fill_gradientn(colors = c("yellow", "orange", "red"), na.value = "grey90")
```


## Plot just the points in solano county
```{r}
solano_sesb_sf <- sesbania_3857_sf %>%
  filter(county == "Solano")

solano_sf <- ca_subset_sf %>%
  filter(county_name == "Solano")

ggplot() +
  geom_sf(data = solano_sf) +
  geom_sf(data = solano_sesb_sf, color = "red")
```

## Make interactive map
```{r}
### set tmap interactive mode
tmap_mode("view")

tm_shape(ca_subset_sf) +
  tm_fill("land_area", palette = "BuGn") +
  tm_shape(sesbania_3857_sf) +
  tm_dots()
```

